//------------------------------------------------------------------------------
// <auto-generated>
// Author:zengnanhua QQ:418852693
// </auto-generated>
//------------------------------------------------------------------------------

using Web.IRespository;
using Web.EFEntity;
namespace Web.IRespository
{
    using System;
    using System.Collections.Generic;
    
    public partial interface IR_Role_MenuRespository:IBaseRespository<R_Role_Menu>
    {
    
    }
}
