//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuService:Web.Service.BaseService<Web.EFEntity.Menu>,Web.IService.IMenuService
    {
    	Web.IRespository.IMenuRespository iSonDal = null;
        public override void SetIDAL()
        {
            iSonDal = base.DBSession.MenuRespository;
    		base.iBaseDal = iSonDal;
        }
    }
}
