//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherMenuService:Web.Service.BaseService<Web.EFEntity.OtherMenu>,Web.IService.IOtherMenuService
    {
    	Web.IRespository.IOtherMenuRespository iSonDal = null;
        public override void SetIDAL()
        {
            iSonDal = base.DBSession.OtherMenuRespository;
    		base.iBaseDal = iSonDal;
        }
    }
}
