//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Role_MenuService:Web.Service.BaseService<Web.EFEntity.R_Role_Menu>,Web.IService.IR_Role_MenuService
    {
    	Web.IRespository.IR_Role_MenuRespository iSonDal = null;
        public override void SetIDAL()
        {
            iSonDal = base.DBSession.R_Role_MenuRespository;
    		base.iBaseDal = iSonDal;
        }
    }
}
