//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_UserInfo_RoleService:Web.Service.BaseService<Web.EFEntity.R_UserInfo_Role>,Web.IService.IR_UserInfo_RoleService
    {
    	Web.IRespository.IR_UserInfo_RoleRespository iSonDal = null;
        public override void SetIDAL()
        {
            iSonDal = base.DBSession.R_UserInfo_RoleRespository;
    		base.iBaseDal = iSonDal;
        }
    }
}
