//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleService:Web.Service.BaseService<Web.EFEntity.Role>,Web.IService.IRoleService
    {
    	Web.IRespository.IRoleRespository iSonDal = null;
        public override void SetIDAL()
        {
            iSonDal = base.DBSession.RoleRespository;
    		base.iBaseDal = iSonDal;
        }
    }
}
