//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoService:Web.Service.BaseService<Web.EFEntity.UserInfo>,Web.IService.IUserInfoService
    {
    	Web.IRespository.IUserInfoRespository iSonDal = null;
        public override void SetIDAL()
        {
            iSonDal = base.DBSession.UserInfoRespository;
    		base.iBaseDal = iSonDal;
        }
    }
}
