
 //------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.IRespository
{
    using System;
    public partial interface IDBSession
    {
    	/// <summary>
        /// 1.0 调用EF容器 批量 执行 sql语句
        /// </summary>
        /// <returns></returns>
        int SaveChanges();
        IMenuRespository MenuRespository 
    	{ 
    		get;
    	}
    
        IOtherMenuRespository OtherMenuRespository 
    	{ 
    		get;
    	}
    
        IR_Role_MenuRespository R_Role_MenuRespository 
    	{ 
    		get;
    	}
    
        IR_UserInfo_RoleRespository R_UserInfo_RoleRespository 
    	{ 
    		get;
    	}
    
        IRoleRespository RoleRespository 
    	{ 
    		get;
    	}
    
        IUserInfoRespository UserInfoRespository 
    	{ 
    		get;
    	}
    
    }
}
