//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Respository
{
using Web.EFEntity;
    using System;
    using System.Collections.Generic;
    
    public partial class R_Role_MenuRespository:BaseRespository<R_Role_Menu>,Web.IRespository.IR_Role_MenuRespository
    {
    
    }
}
