//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Respository
{
using Web.EFEntity;
    using System;
    using System.Collections.Generic;
    
    public partial class R_UserInfo_RoleRespository:BaseRespository<R_UserInfo_Role>,Web.IRespository.IR_UserInfo_RoleRespository
    {
    
    }
}
