//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Respository
{
using Web.EFEntity;
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoRespository:BaseRespository<UserInfo>,Web.IRespository.IUserInfoRespository
    {
    
    }
}
