
 //------------------------------------------------------------------------------
// <auto-generated>
// 业务仓储接口，作用：
// 1.调用数据仓储 SaveChanges 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应业务子接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.IService
{
    using System;
    public partial interface IServiceSession
    {
    	/// <summary>
        /// 调用 数据仓储接口的 SaveChanges 帮数据层完成 数据批量提交
        /// </summary>
        /// <returns></returns>
        int SaveChange();
        Web.IService.IMenuService MenuService
    	{ 
    		get;
    	}
    
        Web.IService.IOtherMenuService OtherMenuService
    	{ 
    		get;
    	}
    
        Web.IService.IR_Role_MenuService R_Role_MenuService
    	{ 
    		get;
    	}
    
        Web.IService.IR_UserInfo_RoleService R_UserInfo_RoleService
    	{ 
    		get;
    	}
    
        Web.IService.IRoleService RoleService
    	{ 
    		get;
    	}
    
        Web.IService.IUserInfoService UserInfoService
    	{ 
    		get;
    	}
    
    }
}
