//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EFEntity
{
	public partial class R_Role_Menu
	{
		public R_Role_Menu ToPOCO(){
			return new R_Role_Menu(){
								R_Role_MenuId=this.R_Role_MenuId,
				RoleId=this.RoleId,
				MenuId=this.MenuId,
			};
		}
	}
}
