//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EFEntity
{
	public partial class R_UserInfo_Role
	{
		public R_UserInfo_Role ToPOCO(){
			return new R_UserInfo_Role(){
								R_UserInfo_RoleId=this.R_UserInfo_RoleId,
				UserName=this.UserName,
				RoleId=this.RoleId,
			};
		}
	}
}
