//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Respository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Web.EFEntity;
    
    public partial class WebEntities : DbContext
    {
        public WebEntities()
            : base("name=WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Menu> Menu { get; set; }
        public DbSet<OtherMenu> OtherMenu { get; set; }
        public DbSet<R_Role_Menu> R_Role_Menu { get; set; }
        public DbSet<R_UserInfo_Role> R_UserInfo_Role { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
