
 //------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Respository
{
    using System;
    public partial class DBSession:Web.IRespository.IDBSession
    {
       public int SaveChanges()
       {
          //从线程中获取EF容器对象
          return EFFatory.GetEFContext().SaveChanges();
       }
    
    	Web.IRespository.IMenuRespository _MenuRespository;
        public Web.IRespository.IMenuRespository MenuRespository 
        { 
        	get
        	{
                if (_MenuRespository == null)
                    _MenuRespository = new MenuRespository();
                return _MenuRespository;
        	}
        }
    
    	Web.IRespository.IOtherMenuRespository _OtherMenuRespository;
        public Web.IRespository.IOtherMenuRespository OtherMenuRespository 
        { 
        	get
        	{
                if (_OtherMenuRespository == null)
                    _OtherMenuRespository = new OtherMenuRespository();
                return _OtherMenuRespository;
        	}
        }
    
    	Web.IRespository.IR_Role_MenuRespository _R_Role_MenuRespository;
        public Web.IRespository.IR_Role_MenuRespository R_Role_MenuRespository 
        { 
        	get
        	{
                if (_R_Role_MenuRespository == null)
                    _R_Role_MenuRespository = new R_Role_MenuRespository();
                return _R_Role_MenuRespository;
        	}
        }
    
    	Web.IRespository.IR_UserInfo_RoleRespository _R_UserInfo_RoleRespository;
        public Web.IRespository.IR_UserInfo_RoleRespository R_UserInfo_RoleRespository 
        { 
        	get
        	{
                if (_R_UserInfo_RoleRespository == null)
                    _R_UserInfo_RoleRespository = new R_UserInfo_RoleRespository();
                return _R_UserInfo_RoleRespository;
        	}
        }
    
    	Web.IRespository.IRoleRespository _RoleRespository;
        public Web.IRespository.IRoleRespository RoleRespository 
        { 
        	get
        	{
                if (_RoleRespository == null)
                    _RoleRespository = new RoleRespository();
                return _RoleRespository;
        	}
        }
    
    	Web.IRespository.IUserInfoRespository _UserInfoRespository;
        public Web.IRespository.IUserInfoRespository UserInfoRespository 
        { 
        	get
        	{
                if (_UserInfoRespository == null)
                    _UserInfoRespository = new UserInfoRespository();
                return _UserInfoRespository;
        	}
        }
    
    }
}
