//------------------------------------------------------------------------------
// <auto-generated>
// Author:JamesZou QQ:576948819
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.IService
{
 using Web.EFEntity;
    using System;
    using System.Collections.Generic;
    
    public partial interface IMenuService:Web.IService.IBaseService<Menu>
    {
    
    }
}
